### ISSUE TITLE
There are broken links 

### ISSUE THREAD

**Issue by themisterpaps** [mozdevz/opensource#18]
**What Happened?**
There are broken links 

**What Did You Expect to Happen**
TODO

**Screenshot (If Applicable)**
![image](https://github.com/mozdevz/opensource/assets/50568515/e3d2c5a2-a70e-47da-8f69-cf438e02d700)
![image](https://github.com/mozdevz/opensource/assets/50568515/90417779-70d5-46d1-b450-8f3f401a6ff4)

**Comment by thatfiredev** [comment]
Fixed in #19
